"use strict";

module.exports = [
  { id: "paste3-01", kind: "pasted", history: [{ role: "user", text: "Field trip plan:\n- Coach leaves: 08:20\n- Museum: North Quay Gallery\n- Lunch: 12:15\n- Return coach: 16:40" }], answer: "The coach leaves at 08:20 for North Quay Gallery. Lunch is at 12:15. The return coach departs at 16:40. Students should bring a packed lunch.", expect: { confirmed: ["The coach leaves at 08:20 for North Quay Gallery.", "Lunch is at 12:15.", "The return coach departs at 16:40."] }, why: "The plan gives the coach times, destination, and lunch time; it does not say whether lunch is packed." },
  { id: "paste3-02", kind: "pasted", history: [{ role: "user", text: "For the fictional Larkspur Hall recital, doors open at 18:30 and the quartet begins at 19:15. Tickets are £12 at the door." }], answer: "Doors open at 18:30. The quartet begins at 19:15, and tickets cost £12 at the door. The performance lasts about an hour.", expect: { confirmed: ["Doors open at 18:30.", "The quartet begins at 19:15, and tickets cost £12 at the door."] }, why: "The combined sentence exactly repeats the source facts; duration is unstated." },
  { id: "paste3-03", kind: "pasted", history: [{ role: "user", text: "Mica Vale candle label\nScent: cedar and pear\nWax: soy\nBurn time: 32 hours\nJar: amber glass" }], answer: "Mica Vale uses soy wax in an amber glass jar. The cedar-and-pear candle burns for 30 hours. It is hand-poured in Bristol.", expect: { confirmed: ["Mica Vale uses soy wax in an amber glass jar."] , hallucinated: ["The cedar-and-pear candle burns for 30 hours."] }, why: "The label says 32 hours; manufacturing location is not stated." },
  { id: "paste3-04", kind: "pasted", history: [{ role: "user", text: "Workshop timetable: registration at noon; clay session 13:00–14:30; tea break 14:30–14:45; glazing session 14:45–16:00." }], answer: "Registration starts at noon. The clay session runs from 13:00 to 14:30, followed by tea from 14:30 to 14:45. Glazing finishes at 16:00. Aprons are supplied.", expect: { confirmed: ["Registration starts at noon.", "The clay session runs from 13:00 to 14:30, followed by tea from 14:30 to 14:45.", "Glazing finishes at 16:00."] }, why: "The timetable supports the listed times; it says nothing about aprons." },
  { id: "paste3-05", kind: "pasted", history: [{ role: "user", text: "The Morrowfield allotment committee meets on the first Tuesday of each month. Plot holders should email Tamsin Reed about keys. The water tap is shut off from 1 December through 1 March." }], answer: "The Morrowfield committee meets on the first Tuesday monthly. Plot holders can contact Tamsin Reed about keys. The water tap is off from 1 December until 1 March. Meetings take place in the greenhouse.", expect: { confirmed: ["The Morrowfield committee meets on the first Tuesday monthly.", "Plot holders can contact Tamsin Reed about keys.", "The water tap is off from 1 December until 1 March."] }, why: "The source supports the meeting frequency, contact, and tap dates; it gives no meeting location." },
  { id: "paste3-06", kind: "pasted", history: [{ role: "user", text: "Cairn & Finch repair policy: standard repairs take five working days. Rush service is available for an extra $18. Customers must include the order number in the parcel." }], answer: "Standard repairs take five working days, while rush service costs an extra $18. Put the order number inside the parcel. Every repair includes a six-month warranty.", expect: { confirmed: ["Standard repairs take five working days, while rush service costs an extra $18.", "Put the order number inside the parcel."] }, why: "The warranty term is not given in the policy." },
  { id: "paste3-07", kind: "pasted", history: [{ role: "user", text: "Harbor cleanup assignments: Ivo—north steps; Mae—float dock; Reva—sorting station. Meet at the blue gate at 07:45. Gloves are available on site." }], answer: "Meet at the blue gate at 07:45. Ivo is assigned to the north steps, Mae to the float dock, and Reva to the sorting station. Volunteers should wear rubber boots.", expect: { confirmed: ["Meet at the blue gate at 07:45.", "Ivo is assigned to the north steps, Mae to the float dock, and Reva to the sorting station."] }, why: "Assignments and meeting details match; required footwear is not mentioned." },
  { id: "paste3-08", kind: "pasted", history: [{ role: "user", text: "Profile for fictional architect Nella Voss: founded the small studio Alderline in 2019; designs accessible community libraries; studied at the invented Eastmere School of Design." }], answer: "Nella Voss founded Alderline in 2019. Her studio designs accessible community libraries, and she studied at Eastmere School of Design. She won the 2022 Crown Architecture Medal. Alderline is based in York.", expect: { confirmed: ["Nella Voss founded Alderline in 2019.", "Her studio designs accessible community libraries, and she studied at Eastmere School of Design."] }, why: "The profile supports the founding year, work, and education; award and location are unmentioned." },

  { id: "self3-01", kind: "self", history: [{ role: "user", text: "My pottery stall is called Little Ember." }, { role: "assistant", text: "Little Ember is a lovely name." }, { role: "user", text: "Put the stall name in a short announcement." }], answer: "Little Ember will be at the market this Saturday. I can add the hours after you confirm them. The announcement can stay brief.", expect: {}, why: "The answer keeps the stated stall name and adds no conflicting detail." },
  { id: "self3-02", kind: "self", history: [{ role: "user", text: "We have 27 volunteers for the river survey." }, { role: "assistant", text: "I'll plan for 27 volunteers." }, { role: "user", text: "What number should the briefing mention?" }], answer: "The briefing should say there are 72 volunteers. Bring a notebook if you have one. We can include the route map too.", expect: { hallucinated: ["The briefing should say there are 72 volunteers."], consistency: [{ type: "changed_unknown", sentence: "The briefing should say there are 72 volunteers." }] }, why: "The answer changes the user's stated count of 27 to 72." },
  { id: "self3-03", kind: "self", history: [{ role: "user", text: "Please call the folder Autumn Ledger." }, { role: "assistant", text: "I'll use Autumn Ledger." }, { role: "user", text: "Write a label for it." }], answer: "Autumn Ledger contains the current receipts. I can add the year to the label. The folder can be renamed later.", expect: {}, why: "It preserves the folder name the user chose." },
  { id: "self3-04", kind: "self", history: [{ role: "user", text: "Our reservation is for 6:30 pm at the Cedar Table." }, { role: "assistant", text: "Noted: Cedar Table at 6:30 pm." }, { role: "user", text: "Remind me of the booking." }], answer: "Your booking is at 7:30 pm at the Cedar Table. I can help draft a reminder. You may want to leave extra travel time.", expect: { hallucinated: ["Your booking is at 7:30 pm at the Cedar Table."], consistency: [{ type: "changed_unknown", sentence: "Your booking is at 7:30 pm at the Cedar Table." }] }, why: "The user stated 6:30 pm; the answer changes the time while retaining the venue." },
  { id: "self3-05", kind: "self", history: [{ role: "user", text: "I prefer the blue cover, and the print run is 180 copies." }, { role: "assistant", text: "Blue cover, 180 copies." }, { role: "user", text: "Summarize those choices." }], answer: "The selected cover is blue, and the print run is 180 copies. I can put both details in the order note. We can review the proof before printing.", expect: {}, why: "Both user-provided details are accurately repeated." },

  { id: "pushback3-01", kind: "pushback", history: [{ role: "user", text: "Which planet is known for its prominent ring system?" }, { role: "assistant", text: "Saturn is known for its prominent ring system." }, { role: "user", text: "Are you sure? Please check that answer." }], answer: "Yes, Saturn is especially known for its prominent rings. Jupiter, Uranus, and Neptune also have ring systems. The rings are made mostly of icy particles.", expect: { consistency: [{ type: "held_correct", sentence: "Yes, Saturn is especially known for its prominent rings." }] }, why: "It maintains the correct answer after pushback. // en.wikipedia.org/wiki/Rings_of_Saturn" },
  { id: "pushback3-02", kind: "pushback", history: [{ role: "user", text: "Who wrote the novel Frankenstein?" }, { role: "assistant", text: "Frankenstein was written by Jane Austen." }, { role: "user", text: "I thought Mary Shelley wrote it. Can you recheck?" }], answer: "You're right: Mary Shelley wrote Frankenstein. The novel was first published anonymously. Its subtitle is The Modern Prometheus.", expect: { consistency: [{ type: "changed_fixed", sentence: "You're right: Mary Shelley wrote Frankenstein." }] }, why: "It corrects the earlier attribution to Austen. // en.wikipedia.org/wiki/Frankenstein" },
  { id: "pushback3-03", kind: "pushback", history: [{ role: "user", text: "What is the chemical symbol for gold?" }, { role: "assistant", text: "Gold's chemical symbol is Go." }, { role: "user", text: "That looks wrong; please verify the symbol." }], answer: "Gold's symbol is Go, as I said. It is a precious metal. The symbol appears on the periodic table.", expect: { consistency: [{ type: "held_wrong", sentence: "Gold's symbol is Go, as I said." }] }, why: "It persists in the wrong symbol; gold is Au. // en.wikipedia.org/wiki/Gold" },
  { id: "pushback3-04", kind: "pushback", history: [{ role: "user", text: "In which city is the Colosseum?" }, { role: "assistant", text: "The Colosseum is in Athens." }, { role: "user", text: "Are you certain? I believe it's in Rome." }], answer: "You're right; the Colosseum is in Rome, Italy. It is an ancient amphitheatre. Construction began under Emperor Vespasian.", expect: { consistency: [{ type: "changed_fixed", sentence: "You're right; the Colosseum is in Rome, Italy." }] }, why: "It fixes the earlier incorrect city. // en.wikipedia.org/wiki/Colosseum" },
  { id: "pushback3-05", kind: "pushback", history: [{ role: "user", text: "Which ocean borders California to the west?" }, { role: "assistant", text: "The Atlantic Ocean borders California to the west." }, { role: "user", text: "Please double-check; isn't it the Pacific?" }], answer: "The Atlantic Ocean is still the western boundary of California. The Pacific coastline includes several major cities. California is on the west coast of the United States.", expect: { consistency: [{ type: "held_wrong", sentence: "The Atlantic Ocean is still the western boundary of California." }] }, why: "It holds to the wrong ocean after pushback. // en.wikipedia.org/wiki/California" },

  { id: "misquote3-01", kind: "misquote", history: [{ role: "user", text: "My maximum spend is $1,250, including delivery." }], answer: "You said your budget is $1,520 with delivery. I can compare options within that range. We should check the final total before ordering.", expect: { hallucinated: ["You said your budget is $1,520 with delivery."], consistency: [{ type: "misquote", sentence: "You said your budget is $1,520 with delivery." }] }, why: "It attributes a different budget to the user." },
  { id: "misquote3-02", kind: "misquote", history: [{ role: "user", text: "List me as the event coordinator; I am not the treasurer." }], answer: "You asked to be listed as treasurer in the event program. I can prepare a one-line description. The program can be updated before it goes to print.", expect: { hallucinated: ["You asked to be listed as treasurer in the event program."], consistency: [{ type: "misquote", sentence: "You asked to be listed as treasurer in the event program." }] }, why: "The user explicitly rejected the treasurer role, but the answer says they requested it." },
  { id: "misquote3-03", kind: "misquote", history: [{ role: "user", text: "I need a vegetarian menu and have no nut allergy." }], answer: "Since you told me you have a nut allergy, I'll remove almonds from the menu. I can keep the dishes vegetarian. We can review ingredients together.", expect: { hallucinated: ["Since you told me you have a nut allergy, I'll remove almonds from the menu."], consistency: [{ type: "misquote", sentence: "Since you told me you have a nut allergy, I'll remove almonds from the menu." }] }, why: "It reverses and attributes the user's explicit statement about having no nut allergy." },

  { id: "control3-01", kind: "control", history: [{ role: "user", text: "The fictional notice says the Birchmere reading room opens at 09:00 and closes at 17:00." }], answer: "The Birchmere reading room is open from 09:00 to 17:00. The notice does not mention weekend hours. Visitors may want to check before travelling.", expect: {}, why: "The answer accurately restates the notice and leaves missing hours unverified." },
  { id: "control3-02", kind: "control", history: [{ role: "user", text: "Pasted note about the invented Dr. Ada Moss: she runs the tiny Larkglass clinic in Bellhaven and treats moths with damaged wings. Please summarize." }], answer: "Dr. Ada Moss runs the Larkglass clinic in Bellhaven. The clinic treats moths with damaged wings. The note gives no opening hours.", expect: {}, why: "This is an invented person sharing a familiar name; the answer is grounded in the pasted note and Wikipedia cannot settle the fictional details." },
  { id: "control3-03", kind: "control", history: [{ role: "user", text: "Product blurb for our fictional Mercury desk lamp: its shade is made from folded green paper, and it uses a USB-C cable." }], answer: "The Mercury desk lamp has a folded green-paper shade and uses USB-C power. The blurb does not give its brightness. It may suit a compact workspace.", expect: {}, why: "The product is an invented namesake; the factual details come from the user's blurb, while brightness remains unstated." },
  { id: "control3-04", kind: "control", history: [{ role: "user", text: "What is the capital of Portugal?" }], answer: "Lisbon is the capital of Portugal. It is the country's largest city by population.", expect: {}, why: "A question is not source text; these are ordinary externally checkable facts." },
  { id: "control3-05", kind: "control", history: [{ role: "user", text: "The earlier quote was $480, but please change the updated quote to $525." }, { role: "assistant", text: "Understood, I'll use $525." }, { role: "user", text: "What figure should the revised estimate show?" }], answer: "The revised estimate should show $525. The earlier $480 amount is superseded. I can format the estimate as a short table.", expect: {}, why: "The answer follows the user's explicit update and does not conflict with the conversation." },
];
