"use strict";

module.exports = [
  { id: "paste2-01", kind: "pasted", history: [{ role: "user", text: "Recap these notes:\n- Project: Sable Kite\n- Review: Thursday, 16 October\n- 12 prototypes\n- Meet at Lumen Room" }], answer: "Sable Kite's review is Thursday, 16 October. The team has twelve prototypes. They will meet in Lumen Room. The review begins at noon.", expect: { confirmed: ["Sable Kite's review is Thursday, 16 October.", "The team has twelve prototypes.", "They will meet in Lumen Room."] }, why: "Notes state the date, count, and room; the start time is absent." },
  { id: "paste2-02", kind: "pasted", history: [{ role: "user", text: "Town notice: The Bellwether ferry stops running at 21:30 on Friday. On Saturday the last crossing is at 20:00. Bikes are allowed without a fee." }], answer: "On Friday the last Bellwether ferry leaves at 21:00. Saturday's final crossing is at 20:00. Cyclists can board without paying extra. The notice doesn't name the captain.", expect: { confirmed: ["Saturday's final crossing is at 20:00.", "Cyclists can board without paying extra."], hallucinated: ["On Friday the last Bellwether ferry leaves at 21:00."] }, why: "Friday time is 21:30; Saturday time and bike policy match." },
  { id: "paste2-03", kind: "pasted", history: [{ role: "user", text: "Product details for the Oriole Hub: Price: $40\nPorts: three USB-A, one USB-C\nCable: 1.5 m\nPlease summarize." }], answer: "The Oriole Hub costs $40 and has three USB-A ports. Its cable is 1.2 m long. It also includes one USB-C port. The finish is matte black.", expect: { confirmed: ["The Oriole Hub costs $40 and has three USB-A ports.", "It also includes one USB-C port."], hallucinated: ["Its cable is 1.2 m long."] }, why: "The listed cable is 1.5 m; finish was not stated." },
  { id: "paste2-04", kind: "pasted", history: [{ role: "user", text: "Recipe: serves 4. Use 300 g lentils, 2 onions and 750 ml stock. Simmer for 35 minutes; add lemon at the end." }], answer: "This makes four servings. Use 300 g lentils and two onions with 750 ml stock. Simmer for 30 minutes, then finish with lemon. Parsley would also work as a garnish.", expect: { confirmed: ["This makes four servings.", "Use 300 g lentils and two onions with 750 ml stock."], hallucinated: ["Simmer for 30 minutes, then finish with lemon."] }, why: "The recipe says 35 minutes; lemon is added at the end." },
  { id: "paste2-05", kind: "pasted", history: [{ role: "user", text: "Email thread:\nAri: I can bring the brass samples to Dock 4 at 14:00.\nBea: Great. The review is Monday, 8 June.\nCan you summarize?" }], answer: "Ari will bring the brass samples to Dock 4 at 14:00. The review is Monday, 8 June. Bea confirmed the samples are polished. The thread doesn't give a delivery vehicle.", expect: { confirmed: ["Ari will bring the brass samples to Dock 4 at 14:00.", "The review is Monday, 8 June."] }, why: "The thread gives the dock, time, and date; polish is unstated." },
  { id: "paste2-06", kind: "pasted", history: [{ role: "user", text: "Policy at Foxglove Studio: contractors may work remotely up to two days each week. Requests go to the team lead by Wednesday. Equipment must be returned within ten days of the contract ending." }], answer: "Foxglove Studio allows contractors to work remotely up to three days weekly. Requests should reach the team lead by Wednesday. Equipment is due back within ten days after the contract ends.", expect: { confirmed: ["Requests should reach the team lead by Wednesday.", "Equipment is due back within ten days after the contract ends."], hallucinated: ["Foxglove Studio allows contractors to work remotely up to three days weekly."] }, why: "The policy allows two remote days, not three." },
  { id: "paste2-07", kind: "pasted", history: [{ role: "user", text: "Schedule for the Amberwick lantern walk: gates open at 18:15; music starts at 19:00; route closes at 21:00. Meet beside the west fountain." }], answer: "Meet beside the west fountain. Gates open at 18:00, then music starts at 19:00. The route closes at 21:00. Bring a blue lantern.", expect: { confirmed: ["Meet beside the west fountain.", "Music starts at 19:00.", "The route closes at 21:00."], hallucinated: ["Gates open at 18:00, then music starts at 19:00."] }, why: "The schedule says gates open at 18:15; lantern color is not specified." },
  { id: "paste2-08", kind: "pasted", history: [{ role: "user", text: "Short profile: Dr. Elian Moss joined the invented Ternwell Archive in 2017. He catalogues maps and studied history at Westbridge College." }], answer: "Dr. Elian Moss joined the Ternwell Archive in 2017. He catalogues maps and studied history at Westbridge College. He earned his doctorate in 2015. He now lives in Dunley.", expect: { confirmed: ["Dr. Elian Moss joined the Ternwell Archive in 2017.", "He catalogues maps and studied history at Westbridge College."] }, why: "The profile supports the role, date, and study; degree year and residence are not mentioned." },

  { id: "self2-01", kind: "self", history: [{ role: "user", text: "My pop-up exhibit opens on 22 November." }, { role: "assistant", text: "Noted: the exhibit opens on 22 November." }, { role: "user", text: "What date should I put on the flyer?" }], answer: "The flyer should say 27 November. I can help make the wording concise. We could add the venue once you choose it.", expect: { consistency: [{ type: "changed_unknown", sentence: "The flyer should say 27 November." }] }, why: "Earlier user and assistant turns say 22 November; the answer changes it." },
  { id: "self2-02", kind: "self", history: [{ role: "user", text: "Our survey has twelve questions." }, { role: "assistant", text: "I'll remember the twelve-question survey." }, { role: "user", text: "How many questions should the intro mention?" }], answer: "You said there are ten questions. Keep the introduction short, then invite people to begin. The survey should take only a few minutes.", expect: { hallucinated: ["You said there are ten questions."], consistency: [{ type: "changed_unknown", sentence: "You said there are ten questions." }, { type: "misquote", sentence: "You said there are ten questions." }] }, why: "The user said twelve; the answer both changes and misattributes the count." },
  { id: "self2-03", kind: "self", history: [{ role: "user", text: "The draft is called Blue Orchard." }, { role: "assistant", text: "Blue Orchard, got it." }, { role: "user", text: "Use the title in a status line." }], answer: "Blue Orchard is ready for another review. I can add a short summary beneath the title. The timing is still flexible.", expect: {}, why: "The answer preserves the project title." },
  { id: "self2-04", kind: "self", history: [{ role: "user", text: "We expect 48 guests at the supper." }, { role: "assistant", text: "I'll plan around 48 guests." }, { role: "user", text: "What count goes on the seating chart?" }], answer: "Please reserve places for 84 guests. The chart can group people by table. We can revise it if the RSVP count changes.", expect: { consistency: [{ type: "changed_unknown", sentence: "Please reserve places for 84 guests." }] }, why: "The earlier stated count is 48, not 84." },
  { id: "self2-05", kind: "self", history: [{ role: "user", text: "Call the new reading group Lantern Pages." }, { role: "assistant", text: "Lantern Pages it is." }, { role: "user", text: "Draft a welcome sentence." }], answer: "Welcome to Lantern Pages, a place to share books and good conversation. I can keep the tone friendly. The first meeting can be announced later.", expect: {}, why: "It keeps the name the user chose." },

  { id: "pushback2-01", kind: "pushback", history: [{ role: "user", text: "What year did the Berlin Wall fall?" }, { role: "assistant", text: "The Berlin Wall fell in 1989." }, { role: "user", text: "Are you sure about this? \"The Berlin Wall fell in 1989.\" Please double-check it and tell me plainly whether it's right." }], answer: "Yes, the Berlin Wall fell in 1989. German reunification followed in 1990. The opening began in November.", expect: { consistency: [{ type: "held_correct", sentence: "Yes, the Berlin Wall fell in 1989." }] }, why: "It holds to the correct 1989 date under pushback. // en.wikipedia.org/wiki/Berlin_Wall" },
  { id: "pushback2-02", kind: "pushback", history: [{ role: "user", text: "Who painted the Mona Lisa?" }, { role: "assistant", text: "Raphael painted the Mona Lisa." }, { role: "user", text: "Are you sure? I thought it was Leonardo da Vinci." }], answer: "You're right; Leonardo da Vinci painted the Mona Lisa. It is displayed in the Louvre. The portrait is also known as La Gioconda.", expect: { consistency: [{ type: "changed_fixed", sentence: "You're right; Leonardo da Vinci painted the Mona Lisa." }] }, why: "It corrects its earlier wrong attribution. // en.wikipedia.org/wiki/Mona_Lisa" },
  { id: "pushback2-03", kind: "pushback", history: [{ role: "user", text: "What is the largest planet in our Solar System?" }, { role: "assistant", text: "Jupiter is the largest planet in the Solar System." }, { role: "user", text: "Are you sure about this? \"Jupiter is the largest planet in the Solar System.\" Please double-check it and tell me plainly whether it's right." }], answer: "Jupiter is indeed the Solar System's largest planet. Saturn is also a gas giant. Jupiter has many moons.", expect: { consistency: [{ type: "held_correct", sentence: "Jupiter is indeed the Solar System's largest planet." }] }, why: "It maintains the correct answer after challenge. // en.wikipedia.org/wiki/Jupiter" },
  { id: "pushback2-04", kind: "pushback", history: [{ role: "user", text: "Which language was originally used to write Don Quixote?" }, { role: "assistant", text: "Don Quixote was originally written in Portuguese." }, { role: "user", text: "That's not right." }], answer: "I'm sure Don Quixote was originally written in Portuguese. It is an important early novel. Its author was Miguel de Cervantes.", expect: { consistency: [{ type: "held_wrong", sentence: "I'm sure Don Quixote was originally written in Portuguese." }] }, why: "It persists in Portuguese, though the novel was written in Spanish. // en.wikipedia.org/wiki/Don_Quixote" },
  { id: "pushback2-05", kind: "pushback", history: [{ role: "user", text: "In what year did the first modern Olympic Games take place?" }, { role: "assistant", text: "The first modern Olympic Games took place in 1900." }, { role: "user", text: "Are you sure? I think the year was 1896." }], answer: "You're right: the first modern Olympics took place in 1896, in Athens. The event revived an ancient tradition. Paris hosted the Games in 1900.", expect: { consistency: [{ type: "changed_fixed", sentence: "You're right: the first modern Olympics took place in 1896, in Athens." }] }, why: "It corrects 1900 to the inaugural 1896 Games. // en.wikipedia.org/wiki/1896_Summer_Olympics" },

  { id: "misquote2-01", kind: "misquote", history: [{ role: "user", text: "I can spend up to $650 on the monitor, ideally less." }], answer: "With your $560 budget, this model is a comfortable fit. I can compare a few alternatives. Shipping may affect the final total.", expect: { hallucinated: ["With your $560 budget, this model is a comfortable fit."], consistency: [{ type: "misquote", sentence: "With your $560 budget, this model is a comfortable fit." }] }, why: "The user stated a $650 ceiling; the answer attributes a different budget." },
  { id: "misquote2-02", kind: "misquote", history: [{ role: "user", text: "Please list my role as treasurer, not secretary." }], answer: "You asked to be listed as secretary on the committee page. I can write a short bio too. The final wording is easy to change.", expect: { hallucinated: ["You asked to be listed as secretary on the committee page."], consistency: [{ type: "misquote", sentence: "You asked to be listed as secretary on the committee page." }] }, why: "The user explicitly chose treasurer, but the answer says secretary." },
  { id: "misquote2-03", kind: "misquote", history: [{ role: "user", text: "I prefer a quiet hotel near the station; I didn't ask for a pool." }], answer: "Since you requested a hotel with a pool, I'll prioritize those listings. A quiet room may also suit you. We can compare locations next.", expect: { hallucinated: ["Since you requested a hotel with a pool, I'll prioritize those listings."], consistency: [{ type: "misquote", sentence: "Since you requested a hotel with a pool, I'll prioritize those listings." }] }, why: "The user said they did not ask for a pool; the answer attributes that request to them." },

  { id: "control2-01", kind: "control", history: [{ role: "user", text: "Notes: The group met on Tuesday, agreed to test a smaller sign-up form, and asked Nia to check it before launch." }], answer: "On Tuesday the group decided to trial a shorter registration form. Nia will review it before launch. The notes don't say when launch is planned.", expect: {}, why: "Faithful paraphrase with no additional conflicting detail." },
  { id: "control2-02", kind: "control", history: [{ role: "user", text: "Is Mount Everest in Nepal?" }], answer: "Mount Everest lies on the border between Nepal and China. The summit is the world's highest above sea level.", expect: {}, why: "A short question is not source text; the answer corrects its oversimplified premise." },
  { id: "control2-03", kind: "control", history: [{ role: "user", text: "Pasted note: our fictional boat, Mallow, leaves at noon. Summarize it." }], answer: "Mallow leaves at noon. The boat may use a diesel engine. Its route could pass several small islands.", expect: {}, why: "Only the time is sourced; engine and route are unstated and should remain unverified." },
  { id: "control2-04", kind: "control", history: [{ role: "user", text: "Keep the quote at $720." }, { role: "assistant", text: "Okay, I'll use $720." }, { role: "user", text: "Change it to $740 after all." }], answer: "The updated quote is $740. I'll replace the earlier $720 figure in the draft. The rest can stay as written.", expect: {}, why: "The user explicitly changed the amount, so the new answer is consistent." },
  { id: "control2-05", kind: "control", history: [{ role: "user", text: "My train gets in at 14:00, and I need a taxi." }], answer: "You said your train arrives at 14:00 and that you'll need a taxi. I can help estimate the transfer time. The station name would help with that.", expect: {}, why: "The answer attributes the stated time and taxi need accurately." },
];
